name: contentctl-build
description: Install contentctl-ng and run contentctl-ng build.
inputs:
  build-tarball-path:
    description: Path to the built content tarball produced by contentctl-ng build.
    required: false
    default: dist/DA-ESS-ContentUpdate-latest.tar.gz
runs:
  using: composite
  steps:
    - name: Install contentctl-ng
      uses: ./.github/actions/contentctl-install

    - name: Run build
      shell: bash
      run: |
        contentctl-ng build
        mkdir -p artifacts
        mv "${{ inputs.build-tarball-path }}" artifacts/
