name: Windows Suspicious Configuration Manager Connection
id: 44e76394-ff30-4926-8f52-7f74127f7b9e
version: 1
date: '2026-04-13'
author: Raven Tait, Splunk
status: production
type: TTP
description: |-
    Detects authentication to the System Center Configuration Manager smsexec process.
    SCCM allows administrators to deploy applications located at a specified UNC path to client devices and can select whether they are executed as SYSTEM, as the currently logged in user, or as a specific user.
    An attacker could use this technique to deploy an application on a remote client device as SYSTEM, as the currently logged in user, or as a specific user.
    This can be abused to conduct lateral movement by executing a C2 agent binary from a reachable UNC path (e.g., a readable file share) or by specifying the UNC path of an attacker relay server and forwarding the user's NTLM authentication to another system where they have administrator privileges.
data_source:
    - Windows Event Log Security 4624
search: |-
    `wineventlog_security`
    ElevatedToken="%%1842"
    EventID="4624"
    ProcessName="C:\\Program Files\\Microsoft Configuration Manager\\bin\\X64\\smsexec.exe"
    | fillnull
    | stats count by Computer, ElevatedToken, EventID, ProcessName, action, app, authentication_method, dest, signature, signature_id, src, user
    | `security_content_ctime(firstTime)`
    | `security_content_ctime(lastTime)`
    | `windows_suspicious_configuration_manager_connection_filter`
how_to_implement: The detection is based on data that originates from Endpoint Detection and Response (EDR) agents. These agents are designed to provide security-related telemetry from the endpoints where the agent is installed. To implement this search, you must ingest logs that contain the process GUID, process name, and parent process. Additionally, you must ingest complete command-line executions. These logs must be processed using the appropriate Splunk Technology Add-ons that are specific to the EDR product. The logs must also be mapped to the `Processes` node of the `Endpoint` data model. Use the Splunk Common Information Model (CIM) to normalize the field names and speed up the data modeling process.
known_false_positives: Legitimate administrative tasks using SCCM to deploy applications or scripts through UNC paths may trigger this detection. Filter alerts for authorized administrative configurations and trusted deployment activities.
references:
    - https://github.com/subat0mik/Misconfiguration-Manager/
drilldown_searches:
    - earliest_offset: $info_min_time$
      latest_offset: $info_max_time$
      name: View the detection results for - "$user$" and "$dest$"
      search: '%original_detection_search% | search  user = "$user$" dest = "$dest$"'
    - name: View risk events for the last 7 days for - "$user$" and "$dest$"
      search: '| from datamodel Risk.All_Risk | search normalized_risk_object IN ("$user$", "$dest$") | stats count min(_time) as firstTime max(_time) as lastTime values(search_name) as "Search Name" values(risk_message) as "Risk Message" values(analyticstories) as "Analytic Stories" values(annotations._all) as "Annotations" values(annotations.mitre_attack.mitre_tactic) as "ATT&CK Tactics" by normalized_risk_object | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`'
      earliest_offset: 7d
      latest_offset: "0"
rba:
    message: Potential Suspicious Configuration Manager Connection activity observed on $dest$.
    risk_objects:
        - field: dest
          type: system
          score: 50
    threat_objects: []
tags:
    analytic_story:
        - Active Directory Lateral Movement
        - Windows Service Abuse
        - Windows Persistence Techniques
    asset_type: Endpoint
    mitre_attack_id:
        - T1570
        - T1190
        - T1021.002
        - T1543.003
        - T1078
        - T1134
    product:
        - Splunk Enterprise
        - Splunk Enterprise Security
        - Splunk Cloud
    security_domain: endpoint
tests:
    - name: True Positive Test
      attack_data:
        - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1570/snapattack/snapattack.log
          source: XmlWinEventLog:Security
          sourcetype: XmlWinEventLog
