name: Splunk TA Update

on:
  workflow_dispatch:  # Manually trigger the workflow
  schedule:
    - cron: '55 06 * * *'  # Runs daily at midnight

jobs:
  update-data-source-tas-and-install-yml-apps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: 'develop'
          token: ${{ secrets.DATA_SOURCES_DEPENDABOT }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          architecture: 'x64'  # or the version your script requires

      - name: Install Python Dependencies and ContentCTL and Atomic Red Team
        run: |
          echo "- Contentctl version - $(cat requirements.txt)"
          pip install -r requirements.txt

      - name: Update data source TAs and install.yml apps
        run: |
          echo "Updating data source supported_TA and repo install.yml app versions"
          contentctl-ng update-data-source-tas --content-dirs .
          
          # TODO: Remove this when we are fully compatible with the latest version of the Windows TA
          # Temporarily roll back any automated updates to the Windows TA because we intentionally
          # want to pin to the current version.
          git checkout -- $(grep -rl "https://splunkbase.splunk.com/app/742" data_sources/)
          echo "Changed data source and install.yml files:"
          git status --short -- data_sources install.yml

      - name: Create data source TA and install.yml app update pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.DATA_SOURCES_DEPENDABOT }}
          commit-message: Update data source TA and install.yml app versions
          branch: auto-ta-update-${{ github.run_number }}
          base: develop
          title: Automated Data Source TA and install.yml App Update ${{ github.run_number }}
          body: |
            This PR contains data source supported_TA and install.yml app version updates generated by contentctl-ng.

            The workflow runs:

            ```bash
            contentctl-ng update-data-source-tas --content-dirs .
            ```
          add-paths: |
            data_sources/**
            install.yml
